### PR TITLE
configurable connection retries; configurable connection timeouts

### PR DESCRIPTION
**Pull request by x-wf**
- set connection retries by setting environment variable `CONNECTION_RETRIES` - Default: 3 attempts

- set connection timeout by setting environment variable `CONNECTION_TIMEOUT` - Default: 5 seconds (before it was **1** second)

(p.s. I'm newbish in golang, apologies if there are silly mistakes 😄)

### CODE REVIEW

**Comment by x-wf** [comment]
@Rucknar could you give a review? 👍 thanks!

**Comment by Rucknar** [comment]
Lgtm, thanks for for the commit!

**Comment by x-wf** [comment]
@Rucknar it would be awesome if we could get an update @ https://hub.docker.com/r/infinityworks/docker-hub-exporter

😄 
thank you!

**Comment by Rucknar** [comment]
I’m working with a customer today, I’ll get it done on the train home!

**Pull request merged**
